-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 23:04:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softwave
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softwave
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softwave` DEFAULT CHARACTER SET utf8 ;
USE `softwave` ;

-- -----------------------------------------------------
-- Table `softwave`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`usuario` (
  `prontuario` VARCHAR(7) NOT NULL,
  `permissoes` ENUM('ALUNO', 'PROFESSOR', 'ADMIN') NOT NULL,
  PRIMARY KEY (`prontuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`mensagem` (
  `texto` TEXT NOT NULL,
  `dataEnvio` DATETIME NOT NULL,
  `recebida` TINYINT NOT NULL,
  `mensageiro` VARCHAR(7) NOT NULL,
  `receptor` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`mensageiro`, `receptor`),
  INDEX `fk_mensagem_usuario2_idx` (`receptor` ASC),
  CONSTRAINT `fk_mensagem_usuario1`
    FOREIGN KEY (`mensageiro`)
    REFERENCES `softwave`.`usuario` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensagem_usuario2`
    FOREIGN KEY (`receptor`)
    REFERENCES `softwave`.`usuario` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`areaConhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`areaConhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `softwave`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `lancada` DATETIME NOT NULL,
  `areaConhecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `areaConhecimento_id`),
  INDEX `fk_atividade_areaConhecimento_idx` (`areaConhecimento_id` ASC),
  CONSTRAINT `fk_atividade_areaConhecimento`
    FOREIGN KEY (`areaConhecimento_id`)
    REFERENCES `softwave`.`areaConhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `softwave`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`questao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pergunta` TEXT NOT NULL,
  `respostaCorreta` ENUM('A', 'B', 'C', 'D', 'E') NOT NULL,
  `atividade_id` INT NOT NULL,
  `atividade_areaConhecimento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `atividade_id`, `atividade_areaConhecimento_id`),
  INDEX `fk_questao_atividade1_idx` (`atividade_id` ASC, `atividade_areaConhecimento_id` ASC),
  CONSTRAINT `fk_questao_atividade1`
    FOREIGN KEY (`atividade_id` , `atividade_areaConhecimento_id`)
    REFERENCES `softwave`.`atividade` (`id` , `areaConhecimento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`postagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visivel` TINYINT NOT NULL DEFAULT 1,
  `areaConhecimento_id` INT NOT NULL,
  `usuario_prontuario` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`, `areaConhecimento_id`, `usuario_prontuario`),
  INDEX `fk_postagem_areaConhecimento1_idx` (`areaConhecimento_id` ASC),
  INDEX `fk_postagem_usuario1_idx` (`usuario_prontuario` ASC),
  CONSTRAINT `fk_postagem_areaConhecimento1`
    FOREIGN KEY (`areaConhecimento_id`)
    REFERENCES `softwave`.`areaConhecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_prontuario`)
    REFERENCES `softwave`.`usuario` (`prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`blog` (
  `postagem_id` INT NOT NULL,
  `postagem_areaConhecimento_id` INT NOT NULL,
  `postagem_usuario_prontuario` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`postagem_id`, `postagem_areaConhecimento_id`, `postagem_usuario_prontuario`),
  CONSTRAINT `fk_blog_postagem1`
    FOREIGN KEY (`postagem_id` , `postagem_areaConhecimento_id` , `postagem_usuario_prontuario`)
    REFERENCES `softwave`.`postagem` (`id` , `areaConhecimento_id` , `usuario_prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`comentario` (
  `texto` VARCHAR(1024) NOT NULL,
  `postagem_id` INT NOT NULL,
  `postagem_areaConhecimento_id` INT NOT NULL,
  `postagem_usuario_prontuario` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`postagem_id`, `postagem_areaConhecimento_id`, `postagem_usuario_prontuario`),
  CONSTRAINT `fk_comentario_postagem1`
    FOREIGN KEY (`postagem_id` , `postagem_areaConhecimento_id` , `postagem_usuario_prontuario`)
    REFERENCES `softwave`.`postagem` (`id` , `areaConhecimento_id` , `usuario_prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softwave`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softwave`.`forum` (
  `texto` TEXT NOT NULL,
  `postagem_id` INT NOT NULL,
  `postagem_areaConhecimento_id` INT NOT NULL,
  `postagem_usuario_prontuario` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`postagem_id`, `postagem_areaConhecimento_id`, `postagem_usuario_prontuario`),
  CONSTRAINT `fk_forum_postagem1`
    FOREIGN KEY (`postagem_id` , `postagem_areaConhecimento_id` , `postagem_usuario_prontuario`)
    REFERENCES `softwave`.`postagem` (`id` , `areaConhecimento_id` , `usuario_prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
